<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_myprofile</name>
   <tag></tag>
   <elementGuidId>56f90481-42a6-43fd-8db0-03f0a7408178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href=&quot;#profile&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
