<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pwd</name>
   <tag></tag>
   <elementGuidId>ffda1b72-ba28-4bc8-8b78-b338ab0029fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[placeholder=&quot;Password&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
